services:
  backend:
    build: 
      context: .
      dockerfile: apps/api/Dockerfile.local
    environment:
      JWT_ACCESS: "change_me"
      DB_PATH: "/app/apps/api/data/kaneo.db"
      NODE_ENV: "development"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    ports:
      - 1337:1337
    volumes:
      - ./apps/api:/app/apps/api
      - sqlite_data:/app/apps/api/data
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.local
    environment:
      KANEO_API_URL: "http://localhost:1337"
      NODE_ENV: "development"
    ports:
      - 5173:5173
    volumes:
      - ./apps/web:/app/apps/web
    depends_on:
      - backend
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlite_data:
  rabbitmq_data: